#!/bin/sh

# Set these paths appropriately

BIN=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/bin
CMD=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/cmd
LIB=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
