#!/bin/sh

# Set these paths appropriately

BIN=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/bin
CMD=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/cmd
LIB=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par
LEXFILE=${LIB}/english-lexicon.txt

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
