#!/bin/sh

# Set these paths appropriately

BIN=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/bin
CMD=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/cmd
LIB=/home/david/Classwork/CS124/MachineTranslation/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
